dict/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls",namespace="users")),
    path('', include("dictionary.urls", namespace="dictionary")),
]

dictionary/urls.py
from dictionary import views
from django.urls import path

app_name = "dictionary"

urlpatterns = [
    path('',views.index, name="index"),
    path('add_word/', views.create_word, name="create_word"),
]

users/urls.py
from django.urls import path, include
from users import views

app_name = "users"

urlpatterns = [
    path('login/',views.login, name="login"),
    path('logout/',views.logout, name="logout"),
    path('signup/',views.signup, name="signup"),
]

dictionary/models.py
import uuid
from django.db import models


class Word(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    word = models.CharField(max_length=100)

    def __str__(self):
        return str(self.word)


class WordMeaning(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    word = models.ForeignKey("dictionary.Word", on_delete=models.CASCADE)
    meaning = models.TextField(max_length=255)
    priority = models.IntegerField(null=True)

    def __str__(self):
        return str(self.word)

    
    
    

main/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "username", "password"]
        widgets = {
            "password": forms.widgets.PasswordInput(attrs={
                "class": "one",
                "placeholder": "enter strong password"

            })
        }

dictionary/views.py
from django.shortcuts import render

from dictionary.models import Word, WordMeaning


def index(request):
    if request.method == 'POST':
        search_word = request.POST.get('search_word')

        word = Word.objects.filter(word=search_word)
        error_msg = False
        error = "The word '{}' is not found"

        if word:
            word_meaning = WordMeaning.objects.filter(
                word__in=word
            ).order_by('priority')
            context = {
                "title": "Dictionary",
                "meanings": word_meaning,
                "word": search_word,
                "show": True,
            }
            return render(request, 'dictionary/index.html', context)

        elif search_word == '':
            error_msg="Empty Search"
            context = {
                "title": "Dictionary",
                "word": search_word,
                "show": True,
                "error_msg": error_msg,
            }
            return render(request, 'index.html', context)
            
        else:
            error_msg = error.format(search_word)
            word_meaning = ""

            context = {
                "title": "Dictionary",
                "word": search_word,
                "show": True,
                "error_msg": error_msg,
            }
            return render(request, 'dictionary/index.html', context)


    else:
        context = {
            "title": "Dictionary",
            "searchword": "",
            "word": "",
            "show": False,

        }
        return render(request, 'dictionary/index.html', context)


def create_word(request):
    if request.method == 'POST':
        word = request.POST.get('word')
        meaning = request.POST.get('word_meaning')
        priority = request.POST.get('priority')

        new_word, created = Word.objects.get_or_create(
            word=word
        )
        if new_word:
            WordMeaning.objects.create(
                word=new_word,
                meaning=meaning,
                priority=priority,
            )

    context = {
        "title": "Adding word to dictionary"
    }
    return render(request, "dictionary/addword.html", context)

main/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout 
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User

from users.forms import UserForm
from main.functions import generate_form_errors


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password= request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request,user)

                return HttpResponseRedirect("/")
            
        context={
            "title" : "Login",
            "error" : True,
            "message" : "Invalid username or password"
        }
        return render(request, "users/login.html", context=context)
    else:
        context={
            "title" : "Login"
        }
        return render(request, "users/login.html",context=context)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("dictionary:index"))


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            User.objects.create_user(
                username=instance.username,
                password=instance.password,
                email=instance.email,
                first_name=instance.first_name,
                last_name=instance.last_name
            )

            user = authenticate(request, username=instance.username, password=instance.password)
            auth_login(request,user)

            return HttpResponseRedirect(reverse("dictionary:index"))

        else:
            message = generate_form_errors(form)

            form = UserForm()
            context={
            "title" : "Signup",
            "error" : True,
            "message" : message,
            "form" : form,
            }
            return render(request, "users/signup.html", context=context)

    else:
        form = UserForm()
        context = {
            "title" : "Signup",
            "form" : form,
        }
        return render(request, "users/signup.html", context=context)

templates/dictionary/addword.html
{% extends "dictionary/base.html" %}
{% load static %}
{% block content %}

        <section class="container one">
            <form action="{% url 'dictionary:create_word' %}" method="post" >
                {% csrf_token %}
                <div class="form-field">
                    <label for="word">Word :-</label>
                    <input id='word' type="text" name="word" />
                </div>
                <div class="form-field">
                    <label for="word_meaning">Word meaning :-</label>
                    <textarea name="word_meaning" id="word_meaning" cols="30" rows="10"></textarea>
                </div>
                <div class="form-field">
                    <label for="Priority">Priority :-</label>
                    <select name="priority" id="Priority">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                    </select>
                </div>
                <div class="form-field btn">
                    <input type="submit" value="Add word" />
                    <div><a href="{% url 'dictionary:index' %}">Go Back</a></div>
                </div>
            </form>
        </section>
        {% endblock %}

templates/dictionary/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{{title}}</title>
        <link rel="shortcut icon" href="{% static './images/logo.png' %}"> 
        <link rel="stylesheet" href="{% static './css/add.css' %}" />
        <link rel="stylesheet" href="{% static './css/dict-style.css' %}" />
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
    </html>
    

templates/dictionary/index.html
{% extends "dictionary/base.html" %}
{% load static %}
{% block content %}

        <section id="home">
            <section class="container">
                <header>
                    <h1 class="left">
                        <a href="{% url 'dictionary:index' %}">
                            <img
                                src="{% static 'images/logo.png' %}"
                                alt="Logo"
                            />
                        </a>
                    </h1>
                    <nav>
                        <ul class="items">
                            <li>
                                <a href="{% url 'dictionary:index' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'dictionary:index' %}">Dictionary</a>
                            </li>
                        </ul>
                    </nav>
                    <div class="right">
                        {% if request.user.is_authenticated %}
                            <span class="one">{{request.user.first_name}} {{request.user.last_name}}</span>
                            <a href="{% url 'users:logout' %}" class="login"> Logout </a>
                        {% else %}
                            <a href="{% url 'users:login' %}" class="login"> Login </a>
                        {% endif %}
                    <div>
                </header>
                <div class="box">
                    <h2 class="main">{{title}}</h2>
                    <p class="main">Find the definition of a word</p>
                    <div class="heading">
                        <h3>What word do you want to look up?</h3>
                        <a class="button" href="{% url 'dictionary:create_word' %}">Add Word</a>
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-field">
                            <input type="text" placeholder="Search for a word..." name="search_word" />
                            <button type="submit" class="submit-btn">
                                <img src="{% static './images/search-icon.png' %}" alt="Search" />
                            </button>
                        </div>
                    </form>
                    <ul class="result" >
                        {% if show %}
                            <h2>{{word}}</h2>
                            {% if error_msg %}
                                <p class="error">{{error_msg}}</p>
                            {% endif %}
                            {% for meaning in meanings %}
                                <li>
                                    {{meaning.meaning}}
                                </li>
                            {% endfor %}
                        {% else %}
                            <li>
                                <h2>Search a word</h2>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                
            </section>
        </section> 
        <footer>
            <section class="bottom">
                <p class="footer">Copyright &copy; <a href="{% url 'dictionary:index' %}">{{title}}</a></p>
            </section>
        </footer>

        {% endblock %}

templates/users/auth_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
            name="viewport"
            content="width=<device-width>, initial-scale=1.0"
        />
        <link rel="stylesheet" href="{% static 'css/auth-style.css' %}" />
        <link rel="shortcut icon" href="{% static './images/logo.png' %}"> 
        <title>{{title}}</title>
    </head>
    <body>
        <section class="container">
            {% block content %}{% endblock %}
        </section>
    </body>
</html>

templates/users/login.html
{% extends "users/auth_base.html" %}
{% load static %}
{% block content %}

        <section class="form_container">
            <div class="top">
                <h5>Login Page</h5>
            </div>
            <div class="bottom">
                <form action="" method="post">
                    {% csrf_token %}
                    
                    <div class="input_container">
                        <label for="id_username"> Username </label>
                        <input id="id_username" name="username" type="text" />
                    </div>
                    <div class="input_container">
                        <label for="id_password"> Password </label>
                        <input id="id_password" name="password" type="password" />
                    </div>
                    <div class="submit_container">
                        {% if error %}
                            <p class="error-message">{{message}}</p>
                        {% endif %}
                        <button type="submit">Log in</button>

                        <a href="{% url 'users:signup' %}">Create Account</a>
                      
                    </div>
                </form>
            </div>
        </section>
    {% endblock %}

templates/users/signup.html
{% extends "users/auth_base.html" %}
{% load static %}
{% block content %}
        <section class="form_container">
            <div class="top">
                <h5>Login Page</h5>
            </div>
            <div class="bottom">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="input_container">
                            <label for="{{field.id_for_label}}">{{field.label}}</label>
                            {{field}}
                        </div>
                    {% endfor %}
                    
                    <div class="submit_container">
                        {% if error %}
                            <p class="error-message">{{message}}</p>
                        {% endif %}
                        <button type="submit">Create Account</button>

                        <a href="{% url 'users:login' %}">Login</a>
                    </div>
                </form>
            </div>
        </section>
    {% endblock %}